name=EDP-Platform-Portable
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=Portable Standard C++ providers for ESPressio Platform and Memory abstractions.
paragraph=Concrete Standard C++ implementations of ESPressio atomic, synchronization, byte-operation, and aligned raw-memory-resource capabilities.
category=Other
url=https://espressio.org
architectures=*
includes=ESPressio_Platform_Portable.hpp,ESPressio_Platform_Portable_ByteOperations.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0),EDP-Memory (>=0.1.0 && <0.2.0)
