[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17

lib_deps =
    EDP-Platform-Portable=symlink://../../..
    EDP-Platform=https://github.com/ESPressio-Development-Platform/EDP-Platform.git#main
    EDP-Memory=https://github.com/ESPressio-Development-Platform/EDP-Memory.git#main
    EDP-System=https://github.com/ESPressio-Development-Platform/EDP-System.git#main
