[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++20

build_flags =
    -std=gnu++20

lib_deps =
    EDP-Platform-Portable=symlink://../../..
    EDP-Platform=https://github.com/ESPressio-Development-Platform/EDP-Platform.git#main
    EDP-Memory=https://github.com/ESPressio-Development-Platform/EDP-Memory.git#main
    EDP-System=https://github.com/ESPressio-Development-Platform/EDP-System.git#main
